services:
    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:8.16.1
      container_name: querytube_elasticsearch
      ports:
        - "${ES_PORT}:9200"
      environment:
        - discovery.type=single-node
        - xpack.security.enabled=false
        - xpack.security.http.ssl.enabled=false
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      ulimits:
        memlock:
          soft: -1
          hard: -1

    postgres:
      image: postgres:17.2
      container_name: querytube_postgres
      ports:
        - "${POSTGRES_PORT}:5432"
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=querytube